// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/knowledge-layouts/CompactGrid.tsx": () => import("../components/mockups/knowledge-layouts/CompactGrid.tsx"),
  "./components/mockups/knowledge-layouts/SectionStack.tsx": () => import("../components/mockups/knowledge-layouts/SectionStack.tsx"),
  "./components/mockups/knowledge-layouts/SidebarMasterDetail.tsx": () => import("../components/mockups/knowledge-layouts/SidebarMasterDetail.tsx")
};
